variables:
  DEPLOY_USER: "gitlab-runner-user"
  SERVICE_NAME: "sa-frontend"

stages:
  - test

test:
  image: docker/compose:latest
  tags:
    - $RUNNER_TAG
  stage: test
  environment:
    name: testing
  script:
    - echo "Running tests"
    - docker-compose -f docker-compose-tests.yml -p $CI_COMMIT_SHA build $SERVICE_NAME
    - docker-compose -f docker-compose-tests.yml -p $CI_COMMIT_SHA run --rm $SERVICE_NAME

