version: '3'

services:
  sa-frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.test
    environment:
      - REACT_APP_ENVIRONMENT=testing
      - REACT_APP_API_URL=0.0.0.0:8000
      - REACT_APP_IMAGE_API=https://agri.ltestl.com
      - REACT_APP_CLIMATE_API_BASE_URL=https://api.fieldclimate.com/v2
      - REACT_APP_CLIMATE_API_PUBLIC_KEY=f729364b9d924fc8a4bb702085920b416a472e89d8e28dbb
      - REACT_APP_CLIMATE_API_PRIVATE_KEY=87a853f12aa5344d768f0ecb5d79bdf49372e28bd218f2a3
      - REACT_APP_CLIMATE_STATION_ID=00000146
      - REACT_APP_GOOGLE_APIS_KEY=AIzaSyDdqivRhdU1vv0IJR0zOdk_sc-P4iAFyxY
    command: yarn test -u
    networks:
      - testing

networks:
  testing:

