export * from 'interfaces/IMap';
export * from 'interfaces/IRequests';
export * from 'interfaces/IApp';
export * from 'interfaces/ITechnique';
export * from 'interfaces/IUser';
export * from 'interfaces/IAuth';
export * from 'interfaces/IAuth';
export * from 'interfaces/IError';
export * from 'interfaces/ITable';
